name: bws
description: Basic Web Server in Dart

dependencies:
  unittest: any
  _discoveryapis_commons: ^0.1.0
  browser: ^0.10.0+2
  http: ^0.11.1
  http_server: ^0.9.5+1
  crypto: '>=0.9.0 <0.10.0'
  watcher: "^0.9.7"
